#!/bin/sh

#©keithhedger Mon 12 May 12:47:48 BST 2014 kdhedger68713@gmail.com

. /etc/init.d/init-functions

# Function to create files/directory on boot.
create_files() 
{
# Input to file descriptor 9 and output to stdin (redirection)
	exec 9>&0 < /etc/sysconfig/createfiles

	while read name type perm usr grp dtype maj min junk
		do
# Ignore comments and blank lines.
			case "${name}" in
				""|\#*) continue ;;
			esac

# Ignore existing files.
			if [ ! -e "${name}" ]; then
# Create stuff based on its type.
				case "${type}" in
					dir)
						mkdir "${name}"
						;;
					file)
						:> "${name}"
						 ;;
					dev)
						case "${dtype}" in
							char)
								mknod "${name}" c ${maj} ${min}
								;;
							block)
								mknod "${name}" b ${maj} ${min}
								;;
							pipe)
								mknod "${name}" p
								;;
							*)
								:
#                     log_warning_msg "\nUnknown device type: ${dtype}" 
								;;
						esac
						;;
					*)
#               log_warning_msg "\nUnknown type: ${type}" 
						continue
						;;
				esac

# Set up the permissions, too.
				chown ${usr}:${grp} "${name}"
				chmod ${perm} "${name}"
			fi
		done

# Close file descriptor 9 (end redirection)
exec 0>&9 9>&-
return 0

}

MOUNTRESULT="OK"
prettyMsgStart "Cleaning file systems:"
if [ "${SKIPTMPCLEAN}" = "" ]; then
#         log_info_msg2 " /tmp" 
	cd /tmp && find . -xdev -mindepth 1 ! -name lost+found -delete|| MOUNTRESULT="FAIL"
fi

:> /var/run/utmp

if grep -q '^utmp:' /etc/group ; then
	chmod 664 /var/run/utmp
	chgrp utmp /var/run/utmp
fi

if [ $MOUNTRESULT = "FAIL" ];then
	prettyMsgResult $MOUNTRESULT
	exit 0
fi

if egrep -qv '^(#|$)' /etc/sysconfig/createfiles 2>/dev/null; then
	MOUNTRESULT="OK"
	prettyMsgStart "Creating files and directories"
	create_files      # Always returns 0
fi

prettyMsgResult $MOUNTRESULT



