#!/bin/sh

#©keithhedger Mon 12 May 12:47:48 BST 2014 kdhedger68713@gmail.com

. /etc/init.d/init-functions

# Native English speakers probably don't have /etc/sysconfig/console at all
[ -r /etc/sysconfig/console ] && . /etc/sysconfig/console

MOUNTRESULT="OK"
prettyMsgStart "Setting up Linux console"
# See if we need to do anything
if [ -z "${KEYMAP}" ] && [ -z "${KEYMAP_CORRECTIONS}" ] && [ -z "${FONT}" ] && [ -z "${LEGACY_CHARSET}" ] && ! isTrue "${UNICODE}"; then
		prettyMsgResult $MOUNTRESULT
		exit 0
fi

# There should be no bogus failures below this line!
# Figure out if a framebuffer console is used
	[ -d /sys/class/graphics/fb0 ] && use_fb=1 || use_fb=0

# Figure out the command to set the console into the
# desired mode
      isTrue "${UNICODE}" &&  MODE_COMMAND="echo -en '\033%G' && kbd_mode -u" ||  MODE_COMMAND="echo -en '\033%@\033(K' && kbd_mode -a"

# On framebuffer consoles, font has to be set for each vt in
# UTF-8 mode. This doesn't hurt in non-UTF-8 mode also.

! isTrue "${use_fb}" || [ -z "${FONT}" ] || MODE_COMMAND="${MODE_COMMAND} && setfont ${FONT}"

# Apply that command to all consoles mentioned in
# /etc/inittab. Important: in the UTF-8 mode this should
# happen before setfont, otherwise a kernel bug will
# show up and the unicode map of the font will not be
# used.

for TTY in `grep '^[^#].*respawn:/sbin/agetty' /etc/inittab | grep -o '\btty[[:digit:]]*\b'`
	do
		openvt -f -w -c ${TTY#tty} -- /bin/sh -c "${MODE_COMMAND}"|| MOUNTRESULT="FAIL"
	done

# Set the font (if not already set above) and the keymap
[ "${use_fb}" == "1" ] || [ -z "${FONT}" ] || setfont $FONT || MOUNTRESULT="FAIL"

[ -z "${KEYMAP}" ] || loadkeys ${KEYMAP} >/dev/null 2>&1 || MOUNTRESULT="FAIL"
      
[ -z "${KEYMAP_CORRECTIONS}" ] || loadkeys ${KEYMAP_CORRECTIONS} >/dev/null 2>&1 || MOUNTRESULT="FAIL"

# Convert the keymap from $LEGACY_CHARSET to UTF-8
[ -z "$LEGACY_CHARSET" ] || dumpkeys -c "$LEGACY_CHARSET" | loadkeys -u >/dev/null 2>&1 || MOUNTRESULT="FAIL"

# If any of the commands above failed, the trap at the
# top would set $failed to 1
if [ $MOUNTRESULT = "FAIL" ];then
	prettyMsgResult $MOUNTRESULT
	exit 0
fi
  
prettyMsgResult $MOUNTRESULT


