#!/bin/bash

PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

. /etc/init.d/init-functions

case $1 in
	stop)
		echo "After you press Enter, this system will be powered off"
		waitForUser
		/etc/StartupServices/poweroff -r now
		;;
	*)
		echo "Usage: {stop}"
		exit 1
		;;
esac

exit 0
