#!/bin/sh
########################################################################
# Begin ntpd
#
# Description : Start Network Time Protocol daemon
#
# Author      : DJ Lucas - dj@linuxfromscratch.org
#               Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            ntpd
# Required-Start:      $time $network
# Should-Start:        $remote_fs
# Required-Stop:       $network
# Should-Stop:         $remote_fs
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   NTP Network Time Protocol
# Description:         NTP Syncronizes time with time servers worldwide
# X-LFS-Provided-By:   BLFS / LFS 7.0
### END INIT INFO

. /etc/init.d/init-functions

case "$1" in
	start)
		MOUNTRESULT="OK"
		prettyMsgStart "Starting ntpd"
		/usr/bin/ntpd -g -u ntp:ntp 2>/dev/null
		prettyMsgResult $MOUNTRESULT
		;;

	stop)
		MOUNTRESULT="OK"
		prettyMsgStart "Stopping ntpd"
 		/bin/killall -q /usr/bin/ntpd|| MOUNTRESULT="FAIL"
		prettyMsgResult $MOUNTRESULT
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

# End ntpd

