#!/bin/sh

#©keithhedger Mon 12 May 12:47:48 BST 2014 kdhedger68713@gmail.com

. /etc/init.d/init-functions

MOUNTRESULT="OK"
prettyMsgStart "Retrying failed uevents, if any"

rundir=/run/udev
for file in ${rundir}/tmp-rules--*
	do
		dest=${file##*tmp-rules--}
		[ "$dest" = '*' ] && break
		cat $file >> /etc/udev/rules.d/$dest
		rm -f $file
	done

# Re-trigger the uevents that may have failed, 
# in hope they will succeed now
/bin/sed -e 's/#.*$//' /etc/sysconfig/udev_retry | /bin/grep -v '^$' |while read line
	do
		for subsystem in $line
			do
				/sbin/udevadm trigger --subsystem-match=$subsystem --action=add
			done
	done

# Now wait for udevd to process the uevents we triggered
if ! isTrue "$OMIT_UDEV_RETRY_SETTLE"; then
	/sbin/udevadm settle
fi

prettyMsgResult $MOUNTRESULT


