#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin

for i in /etc/rc.d/rc1.d/*
  do
	  if [ -x "$i" ];then
		  "$i" start
		  if [ $? -ne 0 ];then
			  echo "Problem running $i"
			  /sbin/sulogin
			  exit 1
		  fi
	  fi
  done

