#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin

for i in /etc/rc.d/rc1.d/*
	do
		if [ -x "$i" ];then
			COLUMNS=${COLUMNS:-$(tput cols)} "$i" start
			if [ $? -ne 0 ];then
				echo "Problem running ${i}, after exiting sulogin boot will continue"
				setsid sh -c '/sbin/sulogin <>/dev/tty1 >&0 2>&1'
			fi
		fi
	done
