#!/bin/bash
exec 2>&1

. /etc/init.d/init-functions

PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH
export COLUMNS=${COLUMNS:-$(tput cols)}

#kick all users except root
who | awk '!/root/{ cmd="/sbin/pkill -KILL -u " $1; system(cmd)}'

if [ -f /tmp/slowdown ];then
	SLEEP="/bin/sleep 4"
else
	SLEEP=""
fi

#wait for x to shutdown 
XPID=$(pidof /usr/bin/X)
waitpid $XPID

for i in /etc/rc.d/rc3.d/*
	do
		if [ -x "$i" ];then
			"$i" stop
			$SLEEP
		fi
	done

# Save the alsamixer volumes
if [ -x /usr/sbin/alsactl ]; then
	/usr/sbin/alsactl store &>/dev/null
fi

# Sync the hardware clock
/etc/rc.d/init.d/setclock "stop"

# Turn swapping off
/etc/rc.d/init.d/swap "stop"

# Bring down the localnet
/etc/rc.d/init.d/localnet "stop"

prettyMsgStart "Syncing disks"
/bin/sync
# sleep 3 fixes problems with some hard drives that don't
# otherwise finish syncing before reboot or poweroff
/bin/sleep 3
prettyMsgResult "OK"

#kill udev
udevadm control --exit
killall -q udevd

#kill syslog
killall -q syslogd
killall -q klogd

# Unmount all non-virtual partitions
/etc/rc.d/init.d/mountfs "stop"

if [ "X${SLEEP}" != "X" ];then
	echo "Shutting down/Rebooting now ..."
	sleep 10
fi
