#!/bin/sh

. /etc/init.d/init-functions

case $1 in
	"start")
		MOUNTRESULT="OK"
		if [ -f /fastboot ]; then
			prettyMsgStart  "/fastboot found, no filecheck"
			prettyMsgResult "INFO"
			exit 0
		fi

		prettyMsgStart "Mounting root file system in read-only mode"
		mount -n -o remount,ro / >/dev/null
		if [ ${?} != 0 ]; then
			prettyMsgResult "FAIL"
			prettyMsgStart "Root can't be mounted ro, powering off"
			prettyMsgResult "FAIL"
			waitForUser
			shutdown
			exit 0
		fi
		prettyMsgResult "OK"

		if [ -f /forcefsck ]; then
			prettyMsgStart "/forcefsck found, forcing filecheck" 
			prettyMsgResult "INFO"
			options="-f"
		else
			options=""
		fi
 
		prettyMsgStart "Checking file systems"
		prettyMsgResult "INFO"
		fsck ${options} -a -A -C -T

		error_value=${?}
		case $error_value in
			0)
				prettyMsgStart "File system check"
				prettyMsgResult "OK"
				;;
			1)
				prettyMsgStart "File system errors fixed"
				prettyMsgResult "WARN"
				;;
			2|3)
				prettyMsgStart "File system errors fixed, will reboot in 10 seconds"
				prettyMsgResult "FAIL"
				sleep 10
				$EXECFOLDER/InitForLFS/poweroff -r
				exit 0
				;;
			*)
				prettyMsgStart "Unfixable file system errors found, fix manually"
				prettyMsgResult "FAIL"
				exit 1
				;;
		esac
		;;

	*)
		echo "Usage: ${0} {start}"
		exit 0
		;;
esac

exit 0
