#!/bin/sh

#
# ©K. D. Hedger. Thu  1 Jun 12:59:55 BST 2017 kdhedger68713@gmail.com
#
# This file (checkfs) is part of Init-For-LFS.
#
# rc.d is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option) any later version.

# rc.d is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Init-For-LFS.  If not, see <http://www.gnu.org/licenses/>.
#

. /etc/init.d/init-functions

case $1 in
	"start")
		MOUNTRESULT="OK"
		if [ -f /fastboot ]; then
			prettyMsgStart  "/fastboot found, no filecheck"
			prettyMsgResult "INFO"
			exit 0
		fi

		prettyMsgStart "Mounting root file system in read-only mode"
		mount -n -o remount,ro / >/dev/null
		if [ ${?} != 0 ]; then
			prettyMsgResult "FAIL"
			prettyMsgStart "Root can't be mounted ro, powering off"
			prettyMsgResult "FAIL"
			waitForUser
			shutdown
			exit 0
		fi
		prettyMsgResult "OK"

		if [ -f /forcefsck ]; then
			prettyMsgStart "/forcefsck found, forcing filecheck" 
			prettyMsgResult "INFO"
			options="-f"
		else
			options=""
		fi
 
		prettyMsgStart "Checking file systems"
		prettyMsgResult "INFO"
		fsck ${options} -a -A -C -T

		error_value=${?}
		case $error_value in
			0)
				prettyMsgStart "File system check"
				prettyMsgResult "OK"
				;;
			1)
				prettyMsgStart "File system errors fixed"
				prettyMsgResult "WARN"
				;;
			2|3)
				prettyMsgStart "File system errors fixed, will reboot in 10 seconds"
				prettyMsgResult "FAIL"
				sleep 10
				$BINDIR/poweroff -r
				exit 0
				;;
			*)
				prettyMsgStart "Unfixable file system errors found, fix manually"
				prettyMsgResult "FAIL"
				exit 1
				;;
		esac
		;;

	*)
		echo "Usage: ${0} {start}"
		exit 0
		;;
esac

exit 0
