#!/bin/sh

#
# ©K. D. Hedger. Thu  1 Jun 13:01:06 BST 2017 kdhedger68713@gmail.com
#
# This file (cleanfs) is part of Init-For-LFS.
#
# rc.d is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option) any later version.
#
# rc.d is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Init-For-LFS.  If not, see <http://www.gnu.org/licenses/>.
#

. /etc/init.d/init-functions

# Function to create files/directory on boot.
create_files() 
{
# Input to file descriptor 9 and output to stdin (redirection)
	exec 9>&0 < /etc/sysconfig/createfiles

	while read name type perm usr grp dtype maj min junk
		do
# Ignore comments and blank lines.
			case "${name}" in
				""|\#*) continue ;;
			esac

# Ignore existing files.
			if [ ! -e "${name}" ]; then
# Create stuff based on its type.
				case "${type}" in
					dir)
						mkdir "${name}"
						;;
					file)
						:> "${name}"
						 ;;
					dev)
						case "${dtype}" in
							char)
								mknod "${name}" c ${maj} ${min}
								;;
							block)
								mknod "${name}" b ${maj} ${min}
								;;
							pipe)
								mknod "${name}" p
								;;
							*)
								:
#                     log_warning_msg "\nUnknown device type: ${dtype}" 
								;;
						esac
						;;
					*)
#               log_warning_msg "\nUnknown type: ${type}" 
						continue
						;;
				esac

# Set up the permissions, too.
				chown ${usr}:${grp} "${name}"
				chmod ${perm} "${name}"
			fi
		done

# Close file descriptor 9 (end redirection)
exec 0>&9 9>&-
return 0

}

MOUNTRESULT="OK"
prettyMsgStart "Cleaning file systems:"
if [ "${SKIPTMPCLEAN}" = "" ]; then
#         log_info_msg2 " /tmp" 
	cd /tmp && find . -xdev -mindepth 1 ! -name lost+found -delete|| MOUNTRESULT="FAIL"
fi

:> /var/run/utmp

if grep -q '^utmp:' /etc/group ; then
	chmod 664 /var/run/utmp
	chgrp utmp /var/run/utmp
fi

if [ $MOUNTRESULT = "FAIL" ];then
	prettyMsgResult $MOUNTRESULT
	exit 0
fi

if egrep -qv '^(#|$)' /etc/sysconfig/createfiles 2>/dev/null; then
	MOUNTRESULT="OK"
	prettyMsgStart "Creating files and directories"
	create_files      # Always returns 0
fi

prettyMsgResult $MOUNTRESULT



