#!/bin/sh

#
# ©K. D. Hedger. Thu  1 Jun 13:10:31 BST 2017 kdhedger68713@gmail.com
#
# This file (localnet) is part of Init-For-LFS.
#
# Init-For-LFS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option) any later version.
#
# Init-For-LFS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Init-For-LFS.  If not, see <http://www.gnu.org/licenses/>.
#

. /etc/init.d/init-functions

[ -r /etc/sysconfig/network ] && . /etc/sysconfig/network
[ -r /etc/hostname ] && HOSTNAME=$(cat /etc/hostname)

case "${1}" in
	"start")
		MOUNTRESULT="OK"
		prettyMsgStart "Bringing up the loopback interface"
		ip addr add 127.0.0.1/8 label lo dev lo|| MOUNTRESULT="FAIL"
		ip link set lo up|| MOUNTRESULT="FAIL"
		prettyMsgResult $MOUNTRESULT

		MOUNTRESULT="OK"
		prettyMsgStart "Setting hostname to ${HOSTNAME}"
		hostname ${HOSTNAME}|| MOUNTRESULT="FAIL"
		prettyMsgResult $MOUNTRESULT
		;;

	"stop")
		MOUNTRESULT="OK"
		prettyMsgStart "Bringing down the loopback interface"
		ip link set lo down|| MOUNTRESULT="FAIL"
		prettyMsgResult $MOUNTRESULT
		;;
esac
exit 0
