#!/bin/sh

#
# ©K. D. Hedger. Thu  1 Jun 13:11:33 BST 2017 kdhedger68713@gmail.com
#
# This file (modules) is part of Init-For-LFS.
#
# rc.d is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option) any later version.
#
# rc.d is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Init-For-LFS.  If not, see <http://www.gnu.org/licenses/>.
#


. /etc/init.d/init-functions

[ -e /proc/ksyms -o -e /proc/modules ] || exit 0

MOUNTRESULT="OK"
prettyMsgStart "Checking for module support"
[ -e /proc/ksyms -o -e /proc/modules ] || MOUNTRESULT="FAIL"
prettyMsgResult $MOUNTRESULT

if [ $MOUNTRESULT = "FAIL" ];then
	exit 0
fi

MOUNTRESULT="OK"
prettyMsgStart "Checking for modules file"
[ -r /etc/sysconfig/modules ] || MOUNTRESULT="WARN"
prettyMsgResult $MOUNTRESULT
if [ $MOUNTRESULT = "WARN" ];then
	exit 0
fi

MOUNTRESULT="OK"
prettyMsgStart "Checking for valid entries"
egrep -qv '^($|#)' /etc/sysconfig/modules || MOUNTRESULT="WARN"
prettyMsgResult $MOUNTRESULT
if [ $MOUNTRESULT = "WARN" ];then
	exit 0
fi

prettyMsgStart "Loading modules"
prettyMsgResult "INFO"

	while read module args
		do
			MOUNTRESULT="OK"
# Ignore comments and blank lines.
			case "$module" in
				""|"#"*) continue ;;
			esac

# Attempt to load the module, passing any arguments provided.
			prettyMsgStart "Loading ${module}"
			modprobe ${module} ${args} >/dev/null

# Print the module name if successful, otherwise take note.
			if [ $? -eq 0 ];then
				prettyMsgResult "OK"
			else
 				prettyMsgResult "WARN"
			fi
		done < /etc/sysconfig/modules



