#!/bin/sh

#
# ©K. D. Hedger. Thu  1 Jun 13:12:22 BST 2017 kdhedger68713@gmail.com
#
# This file (mountfs) is part of Init-For-LFS.
#
# Init-For-LFS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option) any later version.
#
# rc.d is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Init-For-LFS.  If not, see <http://www.gnu.org/licenses/>.
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

. /etc/init.d/init-functions

case $1 in
	"start")
		MOUNTRESULT="OK"
		prettyMsgStart "Remounting root file system in read-write mode"
		mount -o remount,rw / >/dev/null|| MOUNTRESULT="FAIL"
		prettyMsgResult $MOUNTRESULT

		rm -f /fastboot /forcefsck

		MOUNTRESULT="OK"
		prettyMsgStart "Mounting remaining file systems"
		mount -a -O no_netdev >/dev/null|| MOUNTRESULT="FAIL"
		prettyMsgResult $MOUNTRESULT
		;;

	"stop")
		MOUNTRESULT="OK"
		prettyMsgStart "Unmounting all other currently mounted file systems"
		umount -f -a -d -r -t notmpfs,nosysfs,nodevtmpfs,noproc,nodevpts >/dev/null|| MOUNTRESULT="FAIL"
		umount -fR /run 2>&1 >/dev/null
		umount -f -a -r >/dev/null|| MOUNTRESULT="FAIL"
		prettyMsgResult "$MOUNTRESULT"
		;;
esac

exit 0
