#!/bin/sh


#
# ©K. D. Hedger. Thu  1 Jun 12:55:23 BST 2017 kdhedger68713@gmail.com
#
# This file (mountvirtfs) is part of Init-For-LFS.
#
# Init-For-LFS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option) any later version.
#
# Init-For-LFS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Init-For-LFS.  If not, see <http://www.gnu.org/licenses/>.
#

. /etc/init.d/init-functions

prettyMsgStart "Mounting virtual file systems:"
prettyMsgResult "INFO"

MOUNTRESULT="OK"

if ! mountpoint /run >/dev/null; then
	MOUNTRESULT="OK"
	prettyMsgStart "Mounting virtual file system: /run"
	mount /run &>/dev/null|| MOUNTRESULT="FAIL"
	prettyMsgResult $MOUNTRESULT
fi

mkdir -p /run/var /run/lock /run/shm
chmod 1777 /run/shm
chmod 1777 /run/lock

if ! mountpoint /proc >/dev/null; then
	MOUNTRESULT="OK"
	prettyMsgStart "Mounting virtual file system: /proc"
	mount -o nosuid,noexec,nodev /proc &>/dev/null|| MOUNTRESULT="FAIL"
	prettyMsgResult $MOUNTRESULT
fi

if ! mountpoint /sys >/dev/null; then
	MOUNTRESULT="OK"
	prettyMsgStart "Mounting virtual file system: /sys" 
	mount -o nosuid,noexec,nodev /sys &>/dev/null|| MOUNTRESULT="FAIL"
	prettyMsgResult $MOUNTRESULT
fi

if ! mountpoint /dev >/dev/null; then
	MOUNTRESULT="OK"
	prettyMsgStart "Mounting virtual file system: /dev" 
	mount -o mode=0755,nosuid /dev &>/dev/null|| MOUNTRESULT="FAIL"
	prettyMsgResult $MOUNTRESULT
fi

mkdir -p /dev/shm||true
if ! mountpoint /dev/shm >/dev/null; then
	MOUNTRESULT="OK"
	prettyMsgStart "Mounting virtual file system: /dev/shm" 
	mount -o nosuid,nodev /dev/shm &>/dev/null|| MOUNTRESULT="FAIL"
	prettyMsgResult $MOUNTRESULT
fi

cp -a /lib/udev/devices/* /dev
ln -sfn /run/shm /dev/shm
     mkdir -p /sys/fs/cgroup||true
if ! mountpoint /dev/shm >/dev/null; then
	MOUNTRESULT="OK"
	prettyMsgStart "Mounting virtual file system: /dev/shm" 
	mount -o nosuid,noexec,nodev /sys/fs/cgroup &>/dev/null|| MOUNTRESULT="FAIL"
	prettyMsgResult $MOUNTRESULT
fi

MOUNTRESULT="OK"
prettyMsgStart "Creating symllinks in /dev ..." 
ln -sf /proc/self/fd/0 /dev/stdin||MOUNTRESULT="FAIL"
ln -sf /proc/self/fd/1 /dev/stdout||MOUNTRESULT="FAIL"
ln -sf /proc/self/fd/2 /dev/stderr||MOUNTRESULT="FAIL"
ln -sf /proc/self/fd /dev/fd||MOUNTRESULT="FAIL"

if [ -e /proc/kcore ]; then
	ln -sf /proc/kcore /dev/core||MOUNTRESULT="FAIL"
fi
prettyMsgResult $MOUNTRESULT    

exit 0
