#!/bin/sh

#
# ©K. D. Hedger. Thu  1 Jun 12:55:23 BST 2017 kdhedger68713@gmail.com

# This file (00-mountvirtfs) is part of Init-For-LFS.

# rc.d is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option) any later version.
#
# rc.d is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Init-For-LFS.  If not, see <http://www.gnu.org/licenses/>.
#

. /etc/init.d/init-functions

prettyMsgStart "Mounting virtual file systems:"
prettyMsgResult "INFO"

MOUNTRESULT="OK"

if ! mountpoint /run >/dev/null; then
	MOUNTRESULT="OK"
	prettyMsgStart "Mounting virtual file system: /run"
	mount /run &>/dev/null|| MOUNTRESULT="FAIL"
	prettyMsgResult $MOUNTRESULT
fi

mkdir -p /run/var /run/lock /run/shm
chmod 1777 /run/shm

if ! mountpoint /proc >/dev/null; then
	MOUNTRESULT="OK"
	prettyMsgStart "Mounting virtual file system: /proc"
	mount -o nosuid,noexec,nodev /proc &>/dev/null|| MOUNTRESULT="FAIL"
	prettyMsgResult $MOUNTRESULT
fi

if ! mountpoint /sys >/dev/null; then
	MOUNTRESULT="OK"
	prettyMsgStart "Mounting virtual file system: /sys" 
	mount -o nosuid,noexec,nodev /sys &>/dev/null|| MOUNTRESULT="FAIL"
	prettyMsgResult $MOUNTRESULT
fi

if ! mountpoint /dev >/dev/null; then
	MOUNTRESULT="OK"
	prettyMsgStart "Mounting virtual file system: /dev" 
	mount -o mode=0755,nosuid /dev &>/dev/null|| MOUNTRESULT="FAIL"
	prettyMsgResult $MOUNTRESULT
fi

cp -a /lib/udev/devices/* /dev
ln -sfn /run/shm /dev/shm
