#!/bin/sh

#
# ©K. D. Hedger. Thu  1 Jun 13:19:30 BST 2017 kdhedger68713@gmail.com
#
# This file (setclock) is part of Init-For-LFS.
#
# Init-For-LFS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option) any later version.
#
# rc.d is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Init-For-LFS.  If not, see <http://www.gnu.org/licenses/>.
#

. /etc/init.d/init-functions

[ -r /etc/sysconfig/clock ] && . /etc/sysconfig/clock

case "${UTC}" in
	yes|true|1)
		CLOCKPARAMS="${CLOCKPARAMS} --utc"
		;;

	no|false|0)
		CLOCKPARAMS="${CLOCKPARAMS} --localtime"
		;;
esac

case $1 in
	"start")
		MOUNTRESULT="OK"
		prettyMsgStart "Setting hardware clock"
		/sbin/hwclock --hctosys ${CLOCKPARAMS} &>/dev/null|| MOUNTRESULT="FAIL"
		prettyMsgResult $MOUNTRESULT
		;;

	"stop")
		MOUNTRESULT="OK"
		prettyMsgStart "Setting hardware clock"
		hwclock --systohc --utc &>/dev/null|| MOUNTRESULT="FAIL"
		prettyMsgResult $MOUNTRESULT
		;;
esac

exit 0
