#!/bin/sh
########################################################################
# Begin sshd
#
# Description : Start sshd daemon
#
# Author      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            sshd
# Required-Start:      $network
# Should-Start:
# Required-Stop:       sendsignals
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts sshd daemon.
# Description:         Starts sshd daemon.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /etc/init.d/init-functions

case "$1" in
	start)
		MOUNTRESULT="OK"
		prettyMsgStart "Starting SSH Server"
		/usr/bin/ssh-keygen -A
		/usr/sbin/sshd 2>&1 >/dev/null || MOUNTRESULT="FAIL"
		prettyMsgResult $MOUNTRESULT
		;;

	stop)
		MOUNTRESULT="OK"
		prettyMsgStart "Stopping SSH Server"
		/bin/kill -9 `cat /run/sshd.pid` 2>>/dev/null|| MOUNTRESULT="FAIL"
		/bin/killall -q /usr/bin/ssh-agent
		prettyMsgResult $MOUNTRESULT
		rm /run/sshd.pid 2>/dev/null
	;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

# End sshd bootscript
