#!/bin/sh

#
# ©K. D. Hedger. Thu  1 Jun 13:21:53 BST 2017 kdhedger68713@gmail.com
#
# This file (sysctl) is part of Init-For-LFS.
#
# rc.d is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option) any later version.
#
# rc.d is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Init-For-LFS.  If not, see <http://www.gnu.org/licenses/>.
#

. /etc/init.d/init-functions

MOUNTRESULT="OK"
if [ -f "/etc/sysctl.conf" ]; then
	prettyMsgStart "Setting kernel runtime parameters"
	sysctl -q -p|| MOUNTRESULT="FAIL"
	prettyMsgResult $MOUNTRESULT
fi



