#!/bin/sh

#
# ©K. D. Hedger. Thu  1 Jun 13:22:34 BST 2017 kdhedger68713@gmail.com
#
# This file (udev) is part of Init-For-LFS.
#
# rc.d is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option) any later version.
#
# rc.d is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Init-For-LFS.  If not, see <http://www.gnu.org/licenses/>.
#

. /etc/init.d/init-functions

prettyMsgStart "Populating /dev with device nodes "
prettyMsgResult "INFO"

if ! grep -q '[[:space:]]sysfs' /proc/mounts; then
	prettyMsgResult "FAIL"
	echo "FAILURE:\n\nUnable to create devices without a SysFS filesystem\n\n"
	echo "This system will be halted and powered off in 5 seconds.\n\n"
	$EXECFOLDER/InitForLFS/poweroff

else
	prettyMsgResult "INFO"
fi

# Udev handles uevents itself, so we don't need to have
# the kernel call out to any binary in response to them
echo > /proc/sys/kernel/hotplug

# Start the udev daemon to continually watch for, and act on,
# uevents
/sbin/udevd --daemon

# Now traverse /sys in order to "coldplug" devices that have
# already been discovered
/sbin/udevadm trigger --action=add    --type=subsystems
/sbin/udevadm trigger --action=add    --type=devices
/sbin/udevadm trigger --action=change --type=devices

# Now wait for udevd to process the uevents we triggered
/sbin/udevadm settle

# If any LVM based partitions are on the system, ensure they
# are activated so they can be used.
if [ -x /sbin/vgchange ]; then /sbin/vgchange -a y >/dev/null; fi 





