#!/bin/sh

#
# ©K. D. Hedger. Thu  1 Jun 13:23:10 BST 2017 kdhedger68713@gmail.com
#
# This file (udev_retry) is part of Init-For-LFS.
#
# rc.d is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# at your option) any later version.
#
# rc.d is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Init-For-LFS.  If not, see <http://www.gnu.org/licenses/>.
#

. /etc/init.d/init-functions

MOUNTRESULT="OK"
prettyMsgStart "Retrying failed uevents, if any"

rundir=/run/udev
for file in ${rundir}/tmp-rules--*
	do
		dest=${file##*tmp-rules--}
		[ "$dest" = '*' ] && break
		cat $file >> /etc/udev/rules.d/$dest
		rm -f $file
	done

# Re-trigger the uevents that may have failed, 
# in hope they will succeed now
/bin/sed -e 's/#.*$//' /etc/sysconfig/udev_retry | /bin/grep -v '^$' |while read line
	do
		for subsystem in $line
			do
				/sbin/udevadm trigger --subsystem-match=$subsystem --action=add
			done
	done

# Now wait for udevd to process the uevents we triggered
if ! isTrue "$OMIT_UDEV_RETRY_SETTLE"; then
	/sbin/udevadm settle
fi

prettyMsgResult $MOUNTRESULT


